apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bigapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ehienabs/eutuxia.git
    targetRevision: HEAD
    path: appset
  destination:
    name: in-cluster
    namespace: development