apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: development
  labels:
    app: frontend
    env: dev
spec:
  selector:
    matchLabels:
      app: frontend
      env: dev
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        app: frontend
        env: dev
    spec:
      volumes:
        - name: html
          emptyDir: {}
      containers:
        - name: nginx
          image: nginxinc/nginx-unprivileged
          imagePullPolicy: Always
          ports:
            - name: nginx
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
          securityContext:
              allowPrivilegeEscalation: false    
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 128Mi
              cpu: 500m 
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
