apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infraApp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ehienabs/efticyhia.git
    targetRevision: HEAD
    path: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system