apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-volume
  namespace: development
spec:
  storageClassName: premium-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi